version: '3'
services:
  laravel:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
      - "6001:6001"
      # - "9000:9000"
    links:
      - mysql
      - redis

  nginx:
    image: nginx:1.25
    # image: nginx:latest
    ports:
      - "80:80"
      # - "6001:6001"
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./storage/logs/nginx:/var/log/nginx
    depends_on:
      - laravel

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: Zoe900091
    volumes:
      - mysql-data:/var/lib/mysql    
    ports:
      - "3306:3306"

  redis:
    image: redis:6.0
    # image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  
volumes:
  mysql-data:
  redis-data: